/**
 * ⚠  SYNTHETIC / NON-SCIENTIFIC DEMO DATA — DO NOT MISTAKE FOR REAL MEASUREMENTS.
 * ============================================================================
 * Every number produced by this class is generated by hand-written parametric
 * formulas (e.g. `sst = 29.0 - 0.5*|lat-12.5|`). It is NOT measured data and NOT
 * numerical-model output. It is used only for ambient/visual demonstration.
 *
 * It is NOT part of the real ocean-data pipeline. Real, source-derived data
 * comes exclusively from the Python ingestion service via OceanDataService
 * (INCOIS ERDDAP Argo observations, and the gridded VAM analysis field through
 * `/api/model/field`). Never route these values into anything scientific, and
 * never label them with a real provenance. Everything here is tagged
 * `synthetic: true` / `dataSource: 'SYNTHETIC_DEMO'` so it cannot be confused
 * with the real API responses.
 * ============================================================================
 *
 * Interfaces (getTemperature/getSalinity/getCurrentVelocity/getDepthSlice/
 * getVolume/findIsoSurface) are retained only so the existing ambient visuals
 * and the (synthetic) DriftSimulationEngine keep working unchanged.
 */
export class OceanDataManager {
  /** Marker so any consumer can detect this is non-scientific demo data. */
  static SYNTHETIC = true;

  constructor() {
    /** @type {true} Non-scientific demo source — never real measurements. */
    this.synthetic = true;
    this.isReal = false;
    this.layers = {
      temperature: null,
      salinity: null,
      currentU: null,
      currentV: null,
    };
    this.bounds = {
      latMin: 10, latMax: 15,
      lonMin: 78, lonMax: 83,
      depthMin: 0, depthMax: 200,
    };
    this.dataSource = 'SYNTHETIC_DEMO';
    this._initDemoData();
  }

  _initDemoData() {
    // Synthetic parametric demo values only — NOT measured or model data.
    this.dataSource = 'SYNTHETIC_DEMO';
    console.warn('[OceanDataManager] SYNTHETIC demo data (parametric formulas) — ' +
      'NOT real measurements. Real data comes from OceanDataService / the Python ' +
      'ingestion service.');
  }

  /**
   * Get temperature at a 3D point.
   * @param {number} depth - Positive depth in meters
   * @param {number} lat - Latitude
   * @param {number} lon - Longitude
   * @returns {number} Temperature in °C
   */
  getTemperature(depth, lat = 12.5, lon = 80.0) {
    // Realistic Indian Ocean temperature profile
    const sst = 29.0 - 0.5 * Math.abs(lat - 12.5);
    const thermocline = 50; // meters
    const rate = 0.08; // °C per meter below thermocline
    
    if (depth < thermocline) {
      return sst - depth * 0.02;
    }
    return sst - thermocline * 0.02 - (depth - thermocline) * rate;
  }

  /**
   * Get salinity at a 3D point.
   * @param {number} depth - Positive depth in meters
   * @returns {number} Salinity in PSU
   */
  getSalinity(depth, lat = 12.5, lon = 80.0) {
    // Typical salinity profile
    const surface = 34.5 + 0.3 * Math.sin(lat * 0.5);
    return surface + depth * 0.005;
  }

  /**
   * Get current velocity at a 3D point.
   * @returns {{ u: number, v: number }} East/North components in m/s
   */
  getCurrentVelocity(depth, lat = 12.5, lon = 80.0) {
    // Simple surface-intensified current
    const decay = Math.exp(-depth * 0.02);
    return {
      u: 0.3 * decay * Math.sin(lat * 0.3),
      v: 0.15 * decay * Math.cos(lon * 0.2),
    };
  }

  /**
   * Get a depth slice of temperature data.
   * @param {number} depth - Target depth
   * @param {number} resolution - Grid cells per degree
   * @returns {{ data: number[][], bounds: object }}
   */
  getDepthSlice(variable, depth, resolution = 10) {
    const { latMin, latMax, lonMin, lonMax } = this.bounds;
    const rows = Math.ceil((latMax - latMin) * resolution);
    const cols = Math.ceil((lonMax - lonMin) * resolution);
    const data = [];

    for (let r = 0; r < rows; r++) {
      const row = [];
      const lat = latMin + (r / rows) * (latMax - latMin);
      for (let c = 0; c < cols; c++) {
        const lon = lonMin + (c / cols) * (lonMax - lonMin);
        let value;
        switch (variable) {
          case 'temperature': value = this.getTemperature(depth, lat, lon); break;
          case 'salinity': value = this.getSalinity(depth, lat, lon); break;
          default: value = 0;
        }
        row.push(value);
      }
      data.push(row);
    }

    return { data, bounds: this.bounds, depth, variable, synthetic: true, dataSource: 'SYNTHETIC_DEMO' };
  }

  /**
   * Query a volume of ocean data.
   * @returns {{ data: number[][][], bounds: object }}
   */
  getVolume(variable, depthRange = [0, 200], resolution = 5, depthLevels = 10) {
    const slices = [];
    const dStep = (depthRange[1] - depthRange[0]) / depthLevels;
    
    for (let d = 0; d < depthLevels; d++) {
      const depth = depthRange[0] + d * dStep;
      slices.push(this.getDepthSlice(variable, depth, resolution));
    }

    return { slices, depthRange, variable, dataSource: this.dataSource, synthetic: true };
  }

  /**
   * Find iso-surface depth for a target temperature.
   * @param {number} targetTemp - Target temperature
   * @param {number} lat - Latitude
   * @param {number} lon - Longitude
   * @returns {number} Depth in meters where temperature matches
   */
  findIsoSurface(targetTemp, lat = 12.5, lon = 80.0) {
    for (let d = 0; d <= 200; d += 1) {
      if (this.getTemperature(d, lat, lon) <= targetTemp) return d;
    }
    return 200;
  }
}
