// server/scripts/generate_knowledge.js
import fs from 'fs';
import path from 'path';

const creatures = [
  {
    id: 'bannerfish',
    aliases: ['bannerfish.glb', 'bannerfish', 'Bannerfish', 'schooling bannerfish', 'longfin bannerfish'],
    commonName: 'Schooling Bannerfish',
    scientificName: 'Heniochus acuminatus',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Characterized by an elongated fourth dorsal spine forming a long white pennant.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Acanthuriformes',
      family: 'Chaetodontidae',
      genus: 'Heniochus',
      species: 'Heniochus acuminatus'
    },
    habitat: 'Coral reefs, lagoons, and outer reef slopes',
    depthRange: { minMeters: 2, maxMeters: 75, verified: true },
    diet: 'Zooplankton and small benthic invertebrates',
    distribution: 'Indo-Pacific',
    behavior: 'Forms pairs or loose aggregations hovering above coral heads',
    size: 'Up to 25 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'bicolor_angelfish',
    aliases: ['bicolor_angelfish.glb', 'bicolor_angelfish', 'bicolor angelfish', 'Bicolor Angelfish'],
    commonName: 'Bicolor Angelfish',
    scientificName: 'Centropyge bicolor',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Distinctly divided into a yellow anterior and deep blue posterior.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Pomacanthidae',
      genus: 'Centropyge',
      species: 'Centropyge bicolor'
    },
    habitat: 'Lagoon and seaward coral reefs with rich algae and coral cover',
    depthRange: { minMeters: 1, maxMeters: 25, verified: true },
    diet: 'Algae, small crustaceans, and coral polyps',
    distribution: 'Indo-Pacific',
    behavior: 'Secretive among coral branches, lives in small harems',
    size: 'Up to 15 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'black_clownfish',
    aliases: ['black_clownfish.glb', 'black_clownfish', 'black clownfish', 'Black Clownfish', 'black ocellaris'],
    commonName: 'Black Clownfish',
    scientificName: 'Amphiprion ocellaris',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'A naturally occurring melanistic color variant of the common clownfish, living symbiotically with sea anemones.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Pomacentridae',
      genus: 'Amphiprion',
      species: 'Amphiprion ocellaris'
    },
    habitat: 'Shallow coral reefs associated with host sea anemones',
    depthRange: { minMeters: 1, maxMeters: 15, verified: true },
    diet: 'Algae, zooplankton, and anemone food scraps',
    distribution: 'Western Pacific, notably near Darwin, Australia',
    behavior: 'Protective symbiont within host anemone tentacles',
    size: 'Up to 11 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'blue_tang',
    aliases: ['blue_tang.glb', 'blue_tang', 'blue tang', 'Blue Tang', 'palette surgeonfish', 'regal blue tang'],
    commonName: 'Blue Tang',
    scientificName: 'Paracanthurus hepatus',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Possesses razor-sharp caudal spines on either side of the tail base for defense.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Acanthuridae',
      genus: 'Paracanthurus',
      species: 'Paracanthurus hepatus'
    },
    habitat: 'Clear, current-swept coral reefs',
    depthRange: { minMeters: 2, maxMeters: 40, verified: true },
    diet: 'Plankton and filamentous algae',
    distribution: 'Indo-Pacific',
    behavior: 'Schools above coral heads; wedges itself into crevices when alarmed',
    size: 'Up to 31 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'caranx',
    aliases: ['caranx.glb', 'caranx', 'Caranx', 'trevally', 'jack'],
    commonName: 'Caranx',
    scientificName: null,
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Powerful, fast-swimming apex reef predators known for schooling in clear coastal waters.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Carangiformes',
      family: 'Carangidae',
      genus: 'Caranx',
      species: null
    },
    habitat: 'Coastal waters, coral reefs, and open pelagic environments',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Carnivore — smaller fishes, cephalopods, and crustaceans',
    distribution: 'Tropical and subtropical oceans worldwide',
    behavior: 'Fast cruising pelagic predator, frequently hunting in coordinated schools',
    size: 'Varies by species (0.5 to 1.7 m)',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -5.0, maxMeters: -45.0, source: 'simulation fallback' }
  },
  {
    id: 'clown_triggerfish',
    aliases: ['clown_triggerfish.glb', 'clown_triggerfish', 'clown triggerfish', 'Clown Triggerfish'],
    commonName: 'Clown Triggerfish',
    scientificName: 'Balistoides conspicillum',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Features bold white spots on its dark belly and yellow lips, with powerful jaws designed to crush hard-shelled invertebrates.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Tetraodontiformes',
      family: 'Balistidae',
      genus: 'Balistoides',
      species: 'Balistoides conspicillum'
    },
    habitat: 'Outer reef slopes and deep drop-offs',
    depthRange: { minMeters: 1, maxMeters: 75, verified: true },
    diet: 'Sea urchins, crustaceans, mollusks, and coral polyps',
    distribution: 'Indo-Pacific',
    behavior: 'Solitary, highly territorial around reef crevices',
    size: 'Up to 50 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'convict_tang',
    aliases: ['convict_tang.glb', 'convict_tang', 'convict tang', 'Convict Tang', 'convict surgeonfish'],
    commonName: 'Convict Tang',
    scientificName: 'Acanthurus triostegus',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Named for its distinctive vertical black bars resembling a traditional convict uniform.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Acanthuridae',
      genus: 'Acanthurus',
      species: 'Acanthurus triostegus'
    },
    habitat: 'Shallow lagoons, reef flats, and surge zones',
    depthRange: { minMeters: 0, maxMeters: 90, verified: true },
    diet: 'Herbivore — grazes on benthic filamentous algae',
    distribution: 'Indo-Pacific and Eastern Pacific',
    behavior: 'Forms massive feeding aggregations to overwhelm territorial damselfish',
    size: 'Up to 27 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'copperband',
    aliases: ['copperband.glb', 'copperband', 'Copperband', 'copperband butterflyfish'],
    commonName: 'Copperband Butterflyfish',
    scientificName: 'Chelmon rostratus',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Equipped with an elongated tubular snout and a false eye-spot (ocellus) near its dorsal fin to confuse predators.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Chaetodontidae',
      genus: 'Chelmon',
      species: 'Chelmon rostratus'
    },
    habitat: 'Coastal and inner reefs, rocky shores, and estuaries',
    depthRange: { minMeters: 1, maxMeters: 25, verified: true },
    diet: 'Benthic invertebrates, tubeworms, and small crustaceans',
    distribution: 'Indo-West Pacific',
    behavior: 'Monogamous pairs or solitary foragers probing narrow rock fissures',
    size: 'Up to 20 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  }
];

// Add Discus 01 through 09
for (let i = 1; i <= 9; i++) {
  const pad = i.toString().padStart(2, '0');
  creatures.push({
    id: `discus_${pad}`,
    aliases: [`discus_${pad}.glb`, `discus_${pad}`, `discus ${pad}`, `discus ${i}`, `Discus ${i}`, `Discus ${pad}`],
    commonName: `Discus (${pad})`,
    scientificName: null,
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Famed for its laterally compressed disc-shaped body and elaborate parental care where fry feed on parental skin mucus.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Cichliformes',
      family: 'Cichlidae',
      genus: 'Symphysodon',
      species: null
    },
    habitat: 'Calm, slow-moving floodplains and submerged tree tangles',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Omnivore — periphyton, detritus, and aquatic invertebrates',
    distribution: 'Amazon River Basin / captive ornamental cultivars',
    behavior: 'Calm, schooling cichlid maintaining social hierarchies',
    size: 'Up to 20 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  });
}

creatures.push(
  {
    id: 'double_saddle',
    aliases: ['double_saddle.glb', 'double_saddle', 'double saddle', 'Double Saddle', 'double-saddle butterflyfish', 'double saddle butterflyfish'],
    commonName: 'Double-saddle Butterflyfish',
    scientificName: 'Chaetodon ufalensis',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Distinguished by two prominent dark wedge-shaped saddle markings across its yellow and white flank.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Chaetodontidae',
      genus: 'Chaetodon',
      species: 'Chaetodon ufalensis'
    },
    habitat: 'Reef edges, drop-offs, and coral-rich slopes',
    depthRange: { minMeters: 1, maxMeters: 30, verified: true },
    diet: 'Coral polyps, polychaete tentacles, and small crustaceans',
    distribution: 'Indo-Pacific',
    behavior: 'Frequently swims in pairs along reef flats',
    size: 'Up to 20 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'emperor_angelfish',
    aliases: ['emperor_angelfish.glb', 'emperor_angelfish', 'emperor angelfish', 'Emperor Angelfish'],
    commonName: 'Emperor Angelfish',
    scientificName: 'Pomacanthus imperator',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Undergoes a dramatic transformation from juvenile concentric blue-and-white rings to brilliant adult horizontal yellow-and-blue stripes.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Pomacanthidae',
      genus: 'Pomacanthus',
      species: 'Pomacanthus imperator'
    },
    habitat: 'Coral-rich seaward reefs, lagoons, and channel ledges',
    depthRange: { minMeters: 1, maxMeters: 100, verified: true },
    diet: 'Sponges, tunicates, and encrusting organisms',
    distribution: 'Indo-Pacific',
    behavior: 'Solitary or in harem pairs; territorial around shelter caves',
    size: 'Up to 40 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'flame_angelfish',
    aliases: ['flame_angelfish.glb', 'flame_angelfish', 'flame angelfish', 'Flame Angelfish'],
    commonName: 'Flame Angelfish',
    scientificName: 'Centropyge loricula',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Vivid orange-red body with vertical black bars and glowing blue-edged dorsal and anal fins.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Pomacanthidae',
      genus: 'Centropyge',
      species: 'Centropyge loricula'
    },
    habitat: 'Outer reef slopes, drop-offs, and coral rubble fields',
    depthRange: { minMeters: 5, maxMeters: 60, verified: true },
    diet: 'Algae, detritus, and micro-invertebrates',
    distribution: 'Tropical Pacific Ocean',
    behavior: 'Agile, secretive swimmer darting between branching corals',
    size: 'Up to 15 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'fusilier',
    aliases: ['fusilier.glb', 'fusilier', 'Fusilier'],
    commonName: 'Fusilier',
    scientificName: null,
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Streamlined plankton-feeding fish that form large, fast-moving schools in mid-water over coral reefs.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Caesionidae',
      genus: 'Caesio',
      species: null
    },
    habitat: 'Coral reefs and seaward slopes with strong water movement',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Zooplankton',
    distribution: 'Indo-Pacific',
    behavior: 'Dense synchronized schooling along reef crests',
    size: '15 to 40 cm',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'juvenile_angelfish',
    aliases: ['juvenile_angelfish.glb', 'juvenile_angelfish', 'juvenile angelfish', 'Juvenile Angelfish'],
    commonName: 'Juvenile Angelfish',
    scientificName: null,
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Juveniles possess cryptic or disruptive concentric spiral patterns that deter adult aggression.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Pomacanthidae',
      genus: null,
      species: null
    },
    habitat: 'Shallow, protected reef lagoons and inner reef flats',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Algae, worms, and small crustaceans',
    distribution: 'Tropical Indo-Pacific and Atlantic',
    behavior: 'Solitary and reclusive, staying close to protective crevices',
    size: '3 to 10 cm',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'orange_clownfish',
    aliases: ['orange_clownfish.glb', 'orange_clownfish', 'orange clownfish', 'Orange Clownfish', 'percula clownfish', 'clown anemonefish'],
    commonName: 'Orange Clownfish',
    scientificName: 'Amphiprion percula',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Forms a mutualistic relationship with sea anemones, protected by a specialized mucus layer that prevents nematocyst discharge.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Pomacentridae',
      genus: 'Amphiprion',
      species: 'Amphiprion percula'
    },
    habitat: 'Shallow coral reefs in association with host anemones',
    depthRange: { minMeters: 1, maxMeters: 15, verified: true },
    diet: 'Zooplankton, algae, and leftovers from the host anemone',
    distribution: 'Indo-West Pacific and Great Barrier Reef',
    behavior: 'Monogamous pairs with strict size-based hierarchical social structure',
    size: 'Up to 11 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'powder_blue_tang',
    aliases: ['powder_blue_tang.glb', 'powder_blue_tang', 'powder blue tang', 'Powder Blue Tang', 'powder blue surgeonfish'],
    commonName: 'Powder Blue Tang',
    scientificName: 'Acanthurus leucosternon',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Striking pale-blue surgeonfish with a bright yellow dorsal fin and black facial mask, wielding a sharp defensive spine on its caudal peduncle.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Acanthuridae',
      genus: 'Acanthurus',
      species: 'Acanthurus leucosternon'
    },
    habitat: 'Shallow, clear seaward reefs and surge zones',
    depthRange: { minMeters: 0, maxMeters: 25, verified: true },
    diet: 'Benthic algae and detritus',
    distribution: 'Indian Ocean',
    behavior: 'Often solitary and fiercely territorial, occasionally grazing in feeding mobs',
    size: 'Up to 23 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'royal_angelfish',
    aliases: ['royal_angelfish.glb', 'royal_angelfish', 'royal angelfish', 'Royal Angelfish', 'regal angelfish'],
    commonName: 'Royal Angelfish',
    scientificName: 'Pygoplites diacanthus',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Features brilliant vertical bands of orange, white, and violet-blue with a patterned yellow tail.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Pomacanthidae',
      genus: 'Pygoplites',
      species: 'Pygoplites diacanthus'
    },
    habitat: 'Coral-rich lagoons, channels, and outer reef slopes',
    depthRange: { minMeters: 1, maxMeters: 48, verified: true },
    diet: 'Sponges and tunicates',
    distribution: 'Indo-Pacific',
    behavior: 'Solitary or in pairs, cautiously navigating intricate reef arches',
    size: 'Up to 25 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'threadfin',
    aliases: ['threadfin.glb', 'threadfin', 'Threadfin', 'threadfin butterflyfish'],
    commonName: 'Threadfin Butterflyfish',
    scientificName: 'Chaetodon auriga',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Adults develop a prominent trailing filament extending from the dorsal fin and a false black eye-spot.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Chaetodontidae',
      genus: 'Chaetodon',
      species: 'Chaetodon auriga'
    },
    habitat: 'Reef flats, lagoons, and seaward reefs',
    depthRange: { minMeters: 1, maxMeters: 40, verified: true },
    diet: 'Polychaetes, coral polyps, algae, and small sea anemones',
    distribution: 'Indo-Pacific and Red Sea',
    behavior: 'Solitary, in pairs, or in small roaming foraging groups',
    size: 'Up to 23 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'yellow_longnose',
    aliases: ['yellow_longnose.glb', 'yellow_longnose', 'yellow longnose', 'Yellow Longnose', 'yellow longnose butterflyfish'],
    commonName: 'Yellow Longnose Butterflyfish',
    scientificName: 'Forcipiger flavissimus',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Boasts an extremely slender forceps-like snout adapted to snatch prey from narrow coral crevices.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Chaetodontidae',
      genus: 'Forcipiger',
      species: 'Forcipiger flavissimus'
    },
    habitat: 'Exposed seaward reefs and lagoon walls',
    depthRange: { minMeters: 1, maxMeters: 114, verified: true },
    diet: 'Hydroids, fish eggs, small crustaceans, and tubeworm tentacles',
    distribution: 'Widespread throughout the Indo-Pacific and Eastern Pacific',
    behavior: 'Solitary or in pairs, hovering vertically or upside down against overhangs',
    size: 'Up to 22 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'yellow_tang',
    aliases: ['yellow_tang.glb', 'yellow_tang', 'yellow tang', 'Yellow Tang'],
    commonName: 'Yellow Tang',
    scientificName: 'Zebrasoma flavescens',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Intense uniform canary-yellow coloration with a white spine on the caudal peduncle for defense.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Acanthuridae',
      genus: 'Zebrasoma',
      species: 'Zebrasoma flavescens'
    },
    habitat: 'Shallow coral reefs, lagoons, and surge zones',
    depthRange: { minMeters: 1, maxMeters: 81, verified: true },
    diet: 'Herbivore — filament algae and benthic micro-turf',
    distribution: 'Central and Western Pacific, prominently around Hawaii',
    behavior: 'Active diurnal grazer, schooling loosely across reef flats',
    size: 'Up to 20 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'arapaima',
    aliases: ['arapaima.glb', 'arapaima', 'Arapaima', 'pirarucu'],
    commonName: 'Arapaima',
    scientificName: 'Arapaima gigas',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'One of the largest freshwater bony fishes, obligate air-breather that surfaces regularly to take atmospheric oxygen.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Osteoglossiformes',
      family: 'Arapaimidae',
      genus: 'Arapaima',
      species: 'Arapaima gigas'
    },
    habitat: 'Amazon River floodplains, lakes, and oxbows',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Fish, crustaceans, and small land animals falling into water',
    distribution: 'Amazon and Essequibo River basins',
    behavior: 'Cruises surface waters to gulp air into its modified vascularized swim bladder',
    size: 'Up to 3 m, over 150 kg',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.0, maxMeters: -20.0, source: 'simulation fallback' }
  },
  {
    id: 'aurelia',
    aliases: ['aurelia.glb', 'aurelia', 'Aurelia', 'moon jellyfish aurelia'],
    commonName: 'Moon Jellyfish',
    scientificName: 'Aurelia aurita',
    category: 'invertebrate',
    status: 'Active · Simulation entity',
    fact: 'Translucent bell characterized by four prominent horseshoe-shaped gonads visible through the umbrella.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Cnidaria',
      class: 'Scyphozoa',
      order: 'Semaeostomeae',
      family: 'Ulmaridae',
      genus: 'Aurelia',
      species: 'Aurelia aurita'
    },
    habitat: 'Coastal waters, estuaries, and sheltered bays worldwide',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Plankton, copepods, and fish larvae trapped by mucus on its bell',
    distribution: 'Cosmopolitan across temperate and tropical oceans',
    behavior: 'Drifts with ocean currents, pulsing bell gently for minor vertical repositioning',
    size: 'Bell diameter 25 to 40 cm',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -8.0, maxMeters: -50.0, source: 'simulation fallback' }
  },
  {
    id: 'black_marlin',
    aliases: ['black_marlin.glb', 'black_marlin', 'black marlin', 'Black Marlin'],
    commonName: 'Black Marlin',
    scientificName: 'Istiompax indica',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Features rigid pectoral fins that cannot be folded flat against its body, unlike other marlins.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Istiophoriformes',
      family: 'Istiophoridae',
      genus: 'Istiompax',
      species: 'Istiompax indica'
    },
    habitat: 'Tropical and subtropical open ocean waters, often near drop-offs and reefs',
    depthRange: { minMeters: 0, maxMeters: 200, verified: true },
    diet: 'Apex pelagic predator — tuna, squid, and mackerel',
    distribution: 'Indo-Pacific',
    behavior: 'Solitary, high-speed hunter capable of explosive bursts',
    size: 'Up to 4.65 m, over 700 kg',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -15.0, maxMeters: -65.0, source: 'simulation fallback' }
  },
  {
    id: 'chrysaora',
    aliases: ['chrysaora.glb', 'chrysaora', 'Chrysaora', 'sea nettle'],
    commonName: 'Sea Nettle',
    scientificName: null,
    category: 'invertebrate',
    status: 'Active · Simulation entity',
    fact: 'Possesses long, trailing tentacles armed with stinging nematocysts used to capture pelagic prey.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Cnidaria',
      class: 'Scyphozoa',
      order: 'Semaeostomeae',
      family: 'Pelagiidae',
      genus: 'Chrysaora',
      species: null
    },
    habitat: 'Coastal waters and open pelagic zones',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Zooplankton, larval fish, and other gelatinous organisms',
    distribution: 'Atlantic, Pacific, and Indian Oceans',
    behavior: 'Pelagic drifter with trailing stinging tentacle curtain',
    size: 'Bell diameter 20 to 50 cm',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -8.0, maxMeters: -50.0, source: 'simulation fallback' }
  },
  {
    id: 'compass_jellyfish',
    aliases: ['compass_jellyfish.glb', 'compass_jellyfish', 'compass jellyfish', 'Compass Jellyfish'],
    commonName: 'Compass Jellyfish',
    scientificName: 'Chrysaora hysoscella',
    category: 'invertebrate',
    status: 'Active · Simulation entity',
    fact: 'Named for the distinctive brown V-shaped markings on its bell radiating outwards like a compass rose.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Cnidaria',
      class: 'Scyphozoa',
      order: 'Semaeostomeae',
      family: 'Pelagiidae',
      genus: 'Chrysaora',
      species: 'Chrysaora hysoscella'
    },
    habitat: 'Coastal waters and neritic marine environments',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Ctenophores, small fish, copepods, and other jellies',
    distribution: 'Northeast Atlantic, North Sea, and Mediterranean',
    behavior: 'Pelagic swimmer pulsing rhythmic contractions through coastal currents',
    size: 'Bell diameter up to 30 cm',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -8.0, maxMeters: -50.0, source: 'simulation fallback' }
  },
  {
    id: 'hammerhead_shark',
    aliases: ['hammerhead_shark.glb', 'hammerhead_shark', 'hammerhead shark', 'Hammerhead Shark', 'hammerhead'],
    commonName: 'Hammerhead Shark',
    scientificName: null,
    category: 'megafauna',
    status: 'Active · Simulation entity',
    fact: 'The broad cephalofoil enhances 360-degree vision and houses dense ampullae of Lorenzini to detect bioelectric fields of prey buried in sand.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Elasmobranchii',
      order: 'Carcharhiniformes',
      family: 'Sphyrnidae',
      genus: 'Sphyrna',
      species: null
    },
    habitat: 'Warm temperate and tropical waters along continental shelves and island drop-offs',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Stingrays, skates, fish, and cephalopods',
    distribution: 'Worldwide tropical and warm-temperate seas',
    behavior: 'Known to form large schools around seamounts by day and forage solitarily at night',
    size: '2.5 to 6 m',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -8.0, maxMeters: -75.0, source: 'simulation fallback' }
  },
  {
    id: 'jellyfish_moon',
    aliases: ['jellyfish_moon.glb', 'jellyfish_moon', 'jellyfish moon', 'Jellyfish Moon', 'moon jelly'],
    commonName: 'Moon Jellyfish',
    scientificName: 'Aurelia aurita',
    category: 'invertebrate',
    status: 'Active · Simulation entity',
    fact: 'Translucent saucer-shaped bell with short fringe tentacles and four central horseshoe gonads.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Cnidaria',
      class: 'Scyphozoa',
      order: 'Semaeostomeae',
      family: 'Ulmaridae',
      genus: 'Aurelia',
      species: 'Aurelia aurita'
    },
    habitat: 'Sheltered coastal waters, estuaries, and open neritic seas',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Planktonic organisms, protozoans, and mollusk larvae',
    distribution: 'Global temperate and subtropical marine environments',
    behavior: 'Gentle rhythmic pulsing near the surface and mid-water layers',
    size: 'Up to 40 cm bell diameter',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -8.0, maxMeters: -50.0, source: 'simulation fallback' }
  },
  {
    id: 'lined_surgeon',
    aliases: ['lined_surgeon.glb', 'lined_surgeon', 'lined surgeon', 'Lined Surgeon', 'blue-banded surgeonfish', 'clown surgeonfish'],
    commonName: 'Lined Surgeonfish',
    scientificName: 'Acanthurus lineatus',
    category: 'fish',
    status: 'Active · Simulation entity',
    fact: 'Brilliantly patterned with alternating electric-blue, black, and yellow horizontal stripes, equipped with a venomous caudal spine.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Teleostei',
      order: 'Perciformes',
      family: 'Acanthuridae',
      genus: 'Acanthurus',
      species: 'Acanthurus lineatus'
    },
    habitat: 'Exposed coral reef crests and surge-swept reef edges',
    depthRange: { minMeters: 0, maxMeters: 15, verified: true },
    diet: 'Algae grazer with aggressive feeding territory defense',
    distribution: 'Indo-Pacific',
    behavior: 'Highly territorial, defending feeding patches against other herbivores',
    size: 'Up to 38 cm',
    sources: ['World Register of Marine Species (WoRMS)', 'FishBase'],
    simulationDepthEnvelope: { minMeters: -2.5, maxMeters: -32.0, source: 'simulation fallback' }
  },
  {
    id: 'manta_ray',
    aliases: ['manta_ray.glb', 'manta_ray', 'manta ray', 'Manta Ray', 'giant manta ray'],
    commonName: 'Manta Ray',
    scientificName: null,
    category: 'megafauna',
    status: 'Active · Simulation entity',
    fact: 'Possesses cephalic lobes that unfurl to funnel plankton-rich seawater into its mouth while swimming.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Elasmobranchii',
      order: 'Myliobatiformes',
      family: 'Mobulidae',
      genus: 'Mobula',
      species: null
    },
    habitat: 'Pelagic zones, coral reefs, and oceanic islands',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Filter feeder — zooplankton, euphausiids, and fish larvae',
    distribution: 'Tropical, subtropical, and warm temperate waters worldwide',
    behavior: 'Graceful wing-like pectoral fin flapping; frequently visits cleaning stations',
    size: 'Wingspan 3 to 7 m',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -10.0, maxMeters: -60.0, source: 'simulation fallback' }
  },
  {
    id: 'octopus',
    aliases: ['octopus.glb', 'octopus', 'Octopus'],
    commonName: 'Octopus',
    scientificName: null,
    category: 'invertebrate',
    status: 'Active · Simulation entity',
    fact: 'Highly intelligent cephalopod with eight arms bearing suction cups, three hearts, and advanced camouflage capabilities using chromatophores.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Mollusca',
      class: 'Cephalopoda',
      order: 'Octopoda',
      family: null,
      genus: null,
      species: null
    },
    habitat: 'Reefs, rocky seabeds, and coastal dens',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Crabs, mollusks, and small bottom fish',
    distribution: 'Worldwide oceans from shallow tidal pools to deep abyssal plains',
    behavior: 'Solitary, nocturnal hunter; uses jet propulsion and ink for defense',
    size: 'Varies from 10 cm to several meters depending on species',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -115.0, maxMeters: -145.0, source: 'simulation fallback' }
  },
  {
    id: 'orcinus_orca',
    aliases: ['orcinus_orca.glb', 'orcinus_orca', 'orcinus orca', 'Orcinus Orca', 'killer whale', 'orca', 'Orca'],
    commonName: 'Killer Whale (Orca)',
    scientificName: 'Orcinus orca',
    category: 'megafauna',
    status: 'Active · Simulation entity',
    fact: 'The largest member of the oceanic dolphin family (Delphinidae), living in complex matrilineal social pods with distinct hunting cultures.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Delphinidae',
      genus: 'Orcinus',
      species: 'Orcinus orca'
    },
    habitat: 'Cold and temperate coastal and pelagic waters worldwide',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Apex predator — fish, seals, sea lions, and baleen whales',
    distribution: 'Global, from polar ice edges to tropical equator',
    behavior: 'Coordinated pod hunting utilizing echolocation and specialized vocal dialects',
    size: '6 to 8 m, up to 6 tons',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -5.0, maxMeters: -45.0, source: 'simulation fallback' }
  },
  {
    id: 'rhizostoma_pulmo',
    aliases: ['rhizostoma_pulmo.glb', 'rhizostoma_pulmo', 'rhizostoma pulmo', 'Rhizostoma Pulmo', 'barrel jellyfish'],
    commonName: 'Barrel Jellyfish',
    scientificName: 'Rhizostoma pulmo',
    category: 'invertebrate',
    status: 'Active · Simulation entity',
    fact: 'Lacks marginal tentacles; instead uses eight thick, frilled oral arms equipped with numerous small mouth openings for microscopic prey.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Cnidaria',
      class: 'Scyphozoa',
      order: 'Rhizostomeae',
      family: 'Rhizostomatidae',
      genus: 'Rhizostoma',
      species: 'Rhizostoma pulmo'
    },
    habitat: 'Pelagic coastal waters, bays, and estuaries',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Microscopic zooplankton and phytoplankton',
    distribution: 'Northeast Atlantic, Mediterranean, Black Sea, and Sea of Azov',
    behavior: 'Rhythmical pelagic swimming, often swarming in summer coastal blooms',
    size: 'Bell diameter up to 90 cm, weight up to 35 kg',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -8.0, maxMeters: -50.0, source: 'simulation fallback' }
  },
  {
    id: 'sea_turtle',
    aliases: ['sea_turtle.glb', 'sea_turtle', 'sea turtle', 'Sea Turtle', 'green sea turtle', 'turtle'],
    commonName: 'Sea Turtle',
    scientificName: null,
    category: 'megafauna',
    status: 'Active · Simulation entity',
    fact: 'Ancient marine reptiles equipped with hydrodynamic flippers and remarkable geomagnetic navigation to return to natal nesting beaches.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Reptilia',
      order: 'Testudines',
      family: 'Cheloniidae',
      genus: null,
      species: null
    },
    habitat: 'Tropical and subtropical shallow reefs, seagrass beds, and pelagic migration routes',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Herbivorous as adult green turtles; omnivorous as juveniles',
    distribution: 'Warm seas worldwide',
    behavior: 'Solitary swimmer, surfacing regularly to breathe; long-distance oceanic migrations',
    size: 'Up to 1.5 m carapace length, 150 kg',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -5.0, maxMeters: -35.0, source: 'simulation fallback' }
  },
  {
    id: 'shark',
    aliases: ['shark.glb', 'shark', 'Shark'],
    commonName: 'Shark',
    scientificName: null,
    category: 'megafauna',
    status: 'Active · Simulation entity',
    fact: 'Cartilaginous apex predators possessing electroreceptive ampullae of Lorenzini and multiple rows of continuously replaced teeth.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Elasmobranchii',
      order: 'Selachimorpha',
      family: null,
      genus: null,
      species: null
    },
    habitat: 'Marine waters across all ocean basins and depths',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Fish, marine mammals, squid, and crustaceans',
    distribution: 'Global marine distribution',
    behavior: 'Continuous cruising for ram ventilation; keen olfaction and vibration sensing',
    size: 'Varies from 20 cm to over 12 m',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -8.0, maxMeters: -75.0, source: 'simulation fallback' }
  },
  {
    id: 'sperm_whale',
    aliases: ['sperm_whale.glb', 'sperm_whale', 'sperm whale', 'Sperm Whale'],
    commonName: 'Sperm Whale',
    scientificName: 'Physeter macrocephalus',
    category: 'megafauna',
    status: 'Active · Simulation entity',
    fact: 'The largest toothed predator on Earth, boasting the largest brain of any known animal and the spermaceti organ used for echolocation.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Physeteridae',
      genus: 'Physeter',
      species: 'Physeter macrocephalus'
    },
    habitat: 'Deep open ocean waters, submarine canyons, and continental shelf drop-offs',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Deep-sea giant squid, colossal squid, and bathypelagic fishes',
    distribution: 'Ice-free waters worldwide',
    behavior: 'Deep-diving forager holding breath for up to 90 minutes; lives in female nursery pods',
    size: '11 to 18 m, up to 57 tonnes',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -10.0, maxMeters: -90.0, source: 'simulation fallback' }
  },
  {
    id: 'stingray',
    aliases: ['stingray.glb', 'stingray', 'Stingray', 'ray'],
    commonName: 'Stingray',
    scientificName: null,
    category: 'benthic',
    status: 'Active · Simulation entity',
    fact: 'Dorsoventrally flattened cartilaginous bottom-dweller with venomous serrated spines on its tail used strictly for self-defense.',
    classification: {
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class: 'Elasmobranchii',
      order: 'Myliobatiformes',
      family: 'Dasyatidae',
      genus: null,
      species: null
    },
    habitat: 'Sandy lagoons, coastal shallows, and benthic sediment seafloors',
    depthRange: { minMeters: null, maxMeters: null, verified: false },
    diet: 'Mollusks, worms, crustaceans, and small buried bottom fish',
    distribution: 'Tropical and subtropical coastal waters worldwide',
    behavior: 'Burrows into sand with only eyes and spiracles exposed; undulating pectoral fins for locomotion',
    size: 'Disc width 30 cm to 2 m',
    sources: ['World Register of Marine Species (WoRMS)'],
    simulationDepthEnvelope: { minMeters: -115.0, maxMeters: -145.0, source: 'simulation fallback' }
  }
);

// Harmonize both schemas so every single key expected by any consumer is present:
const enriched = creatures.map(c => {
  const isAmbiguous = !c.scientificName;
  return {
    ...c,
    // Nested normalized properties for immediate consumption by Codex, UIManager, and DepthEnvelope
    identity: {
      commonName: c.commonName,
      displayName: c.commonName,
      scientificName: c.scientificName,
      taxon: c.classification.class || c.classification.phylum || 'Marine Organism',
      aphiaId: null,
      confidence: 'HIGH',
      ambiguous: isAmbiguous
    },
    ecology: {
      habitat: c.habitat,
      depth: (c.depthRange && c.depthRange.verified) ? `${c.depthRange.minMeters} – ${c.depthRange.maxMeters} m` : null,
      distribution: c.distribution,
      diet: c.diet
    },
    behavior: {
      movement: c.behavior,
      schooling: c.category === 'fish' || c.id.startsWith('discus') || c.id === 'fusilier' || c.id === 'bannerfish',
      social: c.behavior,
      activity: 'Diurnal',
      verticalMovement: (c.depthRange && c.depthRange.verified) ? 'Reef / Pelagic Range' : null
    },
    morphology: {
      size: c.size,
      lengthMeters: null
    },
    interestingFact: c.fact,
    _meta: {
      source: 'local',
      isLoaded: true,
      isAmbiguous: isAmbiguous,
      schema: 5
    }
  };
});

const outputPath = path.resolve('src/data/marineKnowledge.json');
fs.writeFileSync(outputPath, JSON.stringify(enriched, null, 2), 'utf8');
console.log(`Successfully generated ${enriched.length} creature knowledge records to ${outputPath}`);
